# Site settings
title: "Your Name - Resume"
description: "Professional resume of Your Name"
url: "https://your-github-username.github.io/resume-repo"
baseurl: ""

# Build settings
theme: minimal-mistakes-jekyll

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

# Markdown and syntax highlighting
highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

# Minimal Mistakes theme settings
minimal_mistakes_skin: "colorful" # Using the colorful skin for a vibrant look

# Site author
author:
  name: "Your Name"
  avatar: "/assets/images/your-avatar.jpg"
  bio: "Professional summary about you."
  location: "Your Location"
  email: "your-email@example.com"
  twitter: your-twitter-handle

# Navigation links
nav:
  - title: Home
    url: /
  - title: Resume
    url: /resume/

# Footer links
footer_links:
  - title: GitHub
    url: https://github.com/your-github-username
  - title: LinkedIn
    url: https://linkedin.com/in/your-linkedin-username

# Custom styles
sass:
  custom: /assets/css/custom.scss

# Gems
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata
